### PR TITLE
Added switch mode feature

### PR DESCRIPTION
**Pull request by amanpandey3956**
@ThanushaMandala  added the switch mode feature along with changes you recommended

### CODE REVIEW

**Comment by amanpandey3956** [comment]
hey @ThanushaMandala pls check it

**Comment by amanpandey3956** [comment]
@ThanushaMandala  check out latest pull request i have resolve the issues

**Review by ThanushaMandala — APPROVED** [review]
LGTM

**Comment by amanpandey3956** [comment]
> LGTM

thank you

**Comment by amanpandey3956** [comment]
Hey @ThanushaMandala can you please add hacktoberfest / hacktoberfest-accepted labels

**Comment by amanpandey3956** [comment]
hey @ThanushaMandala can u pls add label of hacktoberfest in this PR

**Pull request merged**
