### PR TITLE
Feature/tool tip

### PR DESCRIPTION
**Pull request by soumytiwari**
modified, "js-file"
added, toolTip

### CODE REVIEW

**Review by ThanushaMandala — APPROVED** [review]
LGTM

**Comment by ThanushaMandala** [comment]
@soumytiwari can u pull in the latest master and check if ur changes for tooltip are working? I can't see tooltip with ur code changes

**Comment by soumytiwari** [comment]
okay cool, am fixing it

and, your issues have "hacktober" tag;
but they are asking, your repo isn't participating in hacktober-fest
could you kindly see upon this??

**Comment by ThanushaMandala** [comment]
can u check now @soumytiwari added tag to repo itself

**Comment by soumytiwari** [comment]
I fixed it, could you see?
Also, yes.. now your repo is participating
Thanks!

**Comment by ThanushaMandala** [comment]
closing as another PR is open #27

**Pull request closed without merging**
