### PR TITLE
Added toggle button for dark/light themes

### PR DESCRIPTION
**Pull request by amanpandey3956**
@ThanushaMandala hey i have added toggle button for dark/light themes

### CODE REVIEW

**Comment by ThanushaMandala** [comment]
@amanpandey3956 pls resolve merge conflicts

**Comment by amanpandey3956** [comment]
> @amanpandey3956 pls resolve merge conflicts

resolved

**Comment by amanpandey3956** [comment]
@ThanushaMandala hey I have resolved the merge conflicts

**Comment by ThanushaMandala** [comment]
hi @amanpandey3956 there have been new changes pushed into the repo due to which your code changes are not working, pls take a look and fix them.

Also remove these headers "Toggle Dark/Light Mode" "Click Below button to switch mode.", 

just add the button label as `switch mode`

**Pull request closed without merging**
