### PR TITLE
Added toggle button

### PR DESCRIPTION
**Pull request by amanpandey3956**
@ThanushaMandala added toggle button for dark/light themes as per user's choice at the top

### CODE REVIEW

**Comment by ThanushaMandala** [comment]
@amanpandey3956 can u pls add some screenshots here for light and dark mode?

**Comment by amanpandey3956** [comment]
Screenshot 2023-10-27 192540

**Comment by amanpandey3956** [comment]
> @amanpandey3956 can u pls add some screenshots here for light and dark mode?

i have added the screenshots pls check it

**Comment by ThanushaMandala** [comment]
@amanpandey3956 can u pls pull in the latest code,

**Comment by amanpandey3956** [comment]
> @amanpandey3956 can u pls pull in the latest code,

i have pulled in the latest code pls check it

**Pull request closed without merging**
